### ISSUE TITLE
Error running "run promptflow" step of login-and-run-evalpf

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/llmops-gha-demo#5]
Forked repo, updated runtime names, and ran action.  Error in the promptflow step.
<img width="980" alt="image" src="https://github.com/Azure/llmops-gha-demo/assets/47987698/21790ca2-c72f-4fee-8da0-f2990756ec23">

log:
Class WorkspaceHubOperations: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/bin/pfazure", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_pf_azure/entry.py", line 82, in main
    entry(command_args)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_pf_azure/entry.py", line 65, in entry
    raise ex
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_pf_azure/entry.py", line 55, in entry
    dispatch_run_commands(args)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_pf_azure/_run.py", line 361, in dispatch_run_commands
    create_run(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_utils.py", line 344, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/_cli/_pf/_run.py", line 629, in create_run
    run = create_func(run=run, stream=stream)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line [18](https://github.com/jakeatmsft/llmops-gha-demo/actions/runs/6176904336/job/16766853462#step:8:19)1, in create_or_update
    rest_obj = self._resolve_dependencies_in_parallel(run=run, runtime=kwargs.get("runtime"), reset=reset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 713, in _resolve_dependencies_in_parallel
    task_results = [task.result() for task in tasks]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 713, in <listcomp>
    task_results = [task.result() for task in tasks]
                    ^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 539, in _resolve_flow
    self._flow_operations._resolve_arm_id_or_upload_dependencies(flow=flow, ignore_tools_json=True)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_flow_opearations.py", line [24](https://github.com/jakeatmsft/llmops-gha-demo/actions/runs/6176904336/job/16766853462#step:8:25)1, in _resolve_arm_id_or_upload_dependencies
    self._try_resolve_code_for_flow(flow=flow, ops=ops, ignore_tools_json=ignore_tools_json)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/promptflow/azure/operations/_flow_opearations.py", line [28](https://github.com/jakeatmsft/llmops-gha-demo/actions/runs/6176904336/job/16766853462#step:8:29)0, in _try_resolve_code_for_flow
    upload_paths += list(traverse_directory(root, files, source_path, prefix, ignore_file=ignore_file))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: traverse_directory() takes 2 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given
Error: Process completed with exit code 1.

**Comment by jakeatmsft** [comment]
[logs_3.zip](https://github.com/Azure/llmops-gha-demo/files/12601468/logs_3.zip)

**Comment by AbeOmor** [comment]
@jakeatmsft This seems like it a PF code version issues, should be fixed now

**Comment by jakeatmsft** [comment]
Thanks @AbeOmor, looks good now:

<img width="982" alt="image" src="https://github.com/Azure/llmops-gha-demo/assets/47987698/4d382d5f-9cfa-42f8-8dac-4e3b4c89507c">
